# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments

# Needed for backward compatibility
gems: [jekyll-paginate]

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'Uplayer Plugin'
tagline:          'New Getlink Google Drive Video Url'
description:      'New Getlink Google Drive Video Url & Wordpress Plugin'
url:              'https://uplayerstream.github.io'
baseurl:          'https://uplayerstream.github.io'

# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/
- text: Search
  url: /search/


# Author Details
author:         'Uplayer Plugin'

#Social Media links (Use complete URL except for email)
dribbble:
email:
facebook:       'https://www.facebook.com/Uplayer-Video-Plugin-421420924919066/'
flickr:
github:         'https://github.com/UPlayerStream'
gplus:          'https://plus.google.com/101751607505059038836/'
instagram:
pinterest:
linkedin:       'https://ae.linkedin.com/in/UPlayerStream/'
rss:
stackoverflow:  'http://stackoverflow.com/'
twitter:        'https://twitter.com/UPlayerStream'

# Google Analytics
gahandler: 'UA-xxxxxxx-1'

#if footersvg is 'true' the social media links will be shown top on the copy right in the footer
footersvg: 'true'

# Disqus
disqushandler: 'uplayer'

# txtpen
txtpenhandler: 'Uplayer'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.9x beta 2
